name: test_backend

on: 
  pull_request:
  push:
    branches: 
      - main
      
jobs:
  test_backend:
  runs-on: ubuntu-latest
  step:
  - name: Checkout
    uses: actions/checkout@v3
    with: 
      go-version: 1.19.x
  - name: Run tests
    run: |
      cd backend
      go test -v ./...
